name: Vue Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20   # ✅ FIXED

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Clean remote folder
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 35.223.218.49
          username: rundoc-test
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            rm -rf /home/rundoc-test/htdocs/test.rundoc.in/*

      - name: Upload dist
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 35.223.218.49
          username: rundoc-test
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist/*"
          target: "/home/rundoc-test/htdocs/test.rundoc.in/"
          

      - name: Set permissions
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 35.223.218.49
          username: rundoc-test
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            chmod -R 755 /home/rundoc-test/htdocs/test.rundoc.in/